import type { Metadata } from "next";
import { ContentPage } from "../_landing/ContentPage";

export const metadata: Metadata = {
  title: "Terms of Service — Arthvion",
  description: "The terms that govern your use of Arthvion.",
};

export default function TermsPage() {
  return (
    <ContentPage
      title="Terms of Service"
      subtitle="The terms that govern your access to and use of Arthvion."
      meta="Last updated: May 2026"
    >
      <h2>1. Agreement</h2>
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) are a binding agreement between you and
        Arthvion (&ldquo;Arthvion,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;). By creating an
        account or using the service, you agree to these Terms. If you don&rsquo;t agree,
        don&rsquo;t use the service.
      </p>

      <h2>2. The service</h2>
      <p>
        Arthvion is a research tool that generates due-diligence memos by aggregating and
        synthesising information from public sources. Output is provided for informational
        purposes only and is generated by automated systems that may contain errors or
        omissions.
      </p>

      <h2>3. Not investment advice</h2>
      <p>
        <strong>
          Arthvion is a research product, not investment advice.
        </strong>{" "}
        Nothing produced by the service is a recommendation to buy, sell, or hold any security,
        nor an offer or solicitation. You are solely responsible for your own investment
        decisions and should independently verify any material information against primary
        sources before relying on it.
      </p>

      <h2>4. Accounts</h2>
      <p>
        You&rsquo;re responsible for keeping your login credentials secure and for all activity
        under your account. Tell us promptly if you suspect unauthorised use. You must provide
        accurate information and be authorised to accept these Terms.
      </p>

      <h2>5. Plans, billing, and credits</h2>
      <p>
        Paid plans are billed in advance on a recurring basis through our payment processor,
        Stripe. Memo credits are allocated per billing cycle and, unless stated otherwise, do
        not roll over. You can cancel at any time through the customer portal; cancellation
        stops future charges but does not retroactively refund the current period except where
        required by law.
      </p>

      <h2>6. Acceptable use</h2>
      <ul>
        <li>Don&rsquo;t use the service for anything unlawful, or to violate the rights of others.</li>
        <li>Don&rsquo;t attempt to disrupt, reverse-engineer, or gain unauthorised access to the service.</li>
        <li>Don&rsquo;t resell or redistribute the output as though it were a primary data source.</li>
      </ul>

      <h2>7. Intellectual property</h2>
      <p>
        The service, including its software and branding, belongs to Arthvion. Subject to these
        Terms, you may use the memos you generate for your own internal business purposes.
      </p>

      <h2>8. Disclaimers and limitation of liability</h2>
      <p>
        The service is provided &ldquo;as is&rdquo; without warranties of any kind. To the
        maximum extent permitted by law, Arthvion is not liable for any indirect, incidental,
        or consequential damages, or for any investment losses arising from your use of the
        service.
      </p>

      <h2>9. Changes</h2>
      <p>
        We may update these Terms from time to time. Material changes will be reflected by an
        updated date above and, where appropriate, additional notice. Continued use after
        changes take effect constitutes acceptance.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions about these Terms? Email{" "}
        <a href="mailto:bimalkumal2004@gmail.com">bimalkumal2004@gmail.com</a>.
      </p>

      <div className="lp-note">
        <p>
          This is a good-faith starting template, not legal advice. Have a qualified attorney
          review and tailor these Terms before relying on them in production.
        </p>
      </div>
    </ContentPage>
  );
}
